// Generated by gencpp from file turn_pkg/Direction.msg
// DO NOT EDIT!


#ifndef TURN_PKG_MESSAGE_DIRECTION_H
#define TURN_PKG_MESSAGE_DIRECTION_H

#include <ros/service_traits.h>


#include <turn_pkg/DirectionRequest.h>
#include <turn_pkg/DirectionResponse.h>


namespace turn_pkg
{

struct Direction
{

typedef DirectionRequest Request;
typedef DirectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Direction
} // namespace turn_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turn_pkg::Direction > {
  static const char* value()
  {
    return "08327713f314dd581e41738ebb789392";
  }

  static const char* value(const ::turn_pkg::Direction&) { return value(); }
};

template<>
struct DataType< ::turn_pkg::Direction > {
  static const char* value()
  {
    return "turn_pkg/Direction";
  }

  static const char* value(const ::turn_pkg::Direction&) { return value(); }
};


// service_traits::MD5Sum< ::turn_pkg::DirectionRequest> should match
// service_traits::MD5Sum< ::turn_pkg::Direction >
template<>
struct MD5Sum< ::turn_pkg::DirectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turn_pkg::Direction >::value();
  }
  static const char* value(const ::turn_pkg::DirectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turn_pkg::DirectionRequest> should match
// service_traits::DataType< ::turn_pkg::Direction >
template<>
struct DataType< ::turn_pkg::DirectionRequest>
{
  static const char* value()
  {
    return DataType< ::turn_pkg::Direction >::value();
  }
  static const char* value(const ::turn_pkg::DirectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turn_pkg::DirectionResponse> should match
// service_traits::MD5Sum< ::turn_pkg::Direction >
template<>
struct MD5Sum< ::turn_pkg::DirectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turn_pkg::Direction >::value();
  }
  static const char* value(const ::turn_pkg::DirectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turn_pkg::DirectionResponse> should match
// service_traits::DataType< ::turn_pkg::Direction >
template<>
struct DataType< ::turn_pkg::DirectionResponse>
{
  static const char* value()
  {
    return DataType< ::turn_pkg::Direction >::value();
  }
  static const char* value(const ::turn_pkg::DirectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURN_PKG_MESSAGE_DIRECTION_H
