// Generated by gencpp from file turn_pkg/DirectionRequest.msg
// DO NOT EDIT!


#ifndef TURN_PKG_MESSAGE_DIRECTIONREQUEST_H
#define TURN_PKG_MESSAGE_DIRECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turn_pkg
{
template <class ContainerAllocator>
struct DirectionRequest_
{
  typedef DirectionRequest_<ContainerAllocator> Type;

  DirectionRequest_()
    : x(0.0)
    , angle(0.0)  {
    }
  DirectionRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::turn_pkg::DirectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turn_pkg::DirectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DirectionRequest_

typedef ::turn_pkg::DirectionRequest_<std::allocator<void> > DirectionRequest;

typedef boost::shared_ptr< ::turn_pkg::DirectionRequest > DirectionRequestPtr;
typedef boost::shared_ptr< ::turn_pkg::DirectionRequest const> DirectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turn_pkg::DirectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turn_pkg::DirectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turn_pkg::DirectionRequest_<ContainerAllocator1> & lhs, const ::turn_pkg::DirectionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turn_pkg::DirectionRequest_<ContainerAllocator1> & lhs, const ::turn_pkg::DirectionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turn_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turn_pkg::DirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turn_pkg::DirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turn_pkg::DirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turn_pkg::DirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turn_pkg::DirectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turn_pkg::DirectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turn_pkg::DirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08327713f314dd581e41738ebb789392";
  }

  static const char* value(const ::turn_pkg::DirectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08327713f314dd58ULL;
  static const uint64_t static_value2 = 0x1e41738ebb789392ULL;
};

template<class ContainerAllocator>
struct DataType< ::turn_pkg::DirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turn_pkg/DirectionRequest";
  }

  static const char* value(const ::turn_pkg::DirectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turn_pkg::DirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 angle\n"
;
  }

  static const char* value(const ::turn_pkg::DirectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turn_pkg::DirectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DirectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turn_pkg::DirectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turn_pkg::DirectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURN_PKG_MESSAGE_DIRECTIONREQUEST_H
